name: xicmpmt
description:  xICMP Monitoring tool is an cross-platform app for real-time and background hosts monitoring.
publish_to: 'none' 
version: 2.0.8+8

environment:
  sdk: '>=3.1.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  intl: ^0.18.1
  path: ^1.8.3
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  drift: ^2.13.1
  sqlite3_flutter_libs: ^0.5.18
  crypto: ^3.0.3
  rxdart: ^0.27.7
  quiver: ^3.2.1  
  equatable: ^2.0.5
  package_info_plus: ^4.2.0
  permission_handler: ^11.0.1
  url_launcher: ^6.2.1
  csv: ^5.1.1
  cupertino_icons: ^1.0.2
  sliver_tools: ^0.2.12
  sentry_flutter: ^7.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  drift_dev: ^2.12.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  assets:
  - assets/